---
theme: jekyll-theme-slate
title: Raspberry Pi PCIe Database
description: Raspberry Pi PCI Express device compatibility database
url: https://pipci.jeffgeerling.com/
fathom_analytics: true

collections:
  boards_cm:
    output: true
  cards_adapter:
    output: true
  cards_gpu:
    output: true
  cards_m2:
    output: true
  cards_network:
    output: true
  cards_multimedia:
    output: true
  cards_other:
    output: true
  cards_storage:
    output: true
  cards_usb:
    output: true
  hats:
    output: true

plugins:
  - jekyll-redirect-from
